### ISSUE TITLE
您库里面的版本应该不是4.0.1

### ISSUE THREAD

**Issue by wangchunjiang** [gzx543097079/AppStorePrivacyInfo#2]
AF 在4.0版本的请求方法多了个 headers 参数,您库里面的没有
![WechatIMG100](https://github.com/gzx543097079/AppStorePrivacyInfo/assets/21255344/ba112f7c-af3e-42a3-98ae-567a3499f60e)

**Comment by wangchunjiang** [comment]
UIkit+AF 文件夹有uiwebview ,苹果已经禁止使用uiwebview,4.0的AF 已经换成wkwebview

**Comment by yanmumama** [comment]
> AF 在4.0版本的请求方法多了个 headers 参数,您库里面的没有 ![WechatIMG100](https://private-user-images.githubusercontent.com/21255344/330360940-ba112f7c-af3e-42a3-98ae-567a3499f60e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Mzc3OTksIm5iZiI6MTcxNjUzNzQ5OSwicGF0aCI6Ii8yMTI1NTM0NC8zMzAzNjA5NDAtYmExMTJmN2MtYWYzZS00MmEzLTk4YWUtNTY3YTM0OTlmNjBlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3NTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTAxNGQyMTczYWRjMjRiY2ZiZjlhYjNjZWJkN2M1OTAwMmE4YTNhMzJmOWQ1M2MyNTVkNmI2MzJhMzFlMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D-c57xpUYTZM9LH6GGcRKn-tUHL8SvB9BGT6eTUPHN4)

大佬这个怎么解决的？

**Comment by gzx543097079** [comment]
后面我查一下 ，AFNetworking 目前测试不需要处理可以直接上

**Comment by wangchunjiang** [comment]
> > AF 在4.0版本的请求方法多了个 headers 参数,您库里面的没有 ![WechatIMG100](https://private-user-images.githubusercontent.com/21255344/330360940-ba112f7c-af3e-42a3-98ae-567a3499f60e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Mzc3OTksIm5iZiI6MTcxNjUzNzQ5OSwicGF0aCI6Ii8yMTI1NTM0NC8zMzAzNjA5NDAtYmExMTJmN2MtYWYzZS00MmEzLTk4YWUtNTY3YTM0OTlmNjBlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3NTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTAxNGQyMTczYWRjMjRiY2ZiZjlhYjNjZWJkN2M1OTAwMmE4YTNhMzJmOWQ1M2MyNTVkNmI2MzJhMzFlMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D-c57xpUYTZM9LH6GGcRKn-tUHL8SvB9BGT6eTUPHN4)
> 
> 大佬这个怎么解决的？

**Comment by wangchunjiang** [comment]
> > AF 在4.0版本的请求方法多了个 headers 参数,您库里面的没有 ![WechatIMG100](https://private-user-images.githubusercontent.com/21255344/330360940-ba112f7c-af3e-42a3-98ae-567a3499f60e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Mzc3OTksIm5iZiI6MTcxNjUzNzQ5OSwicGF0aCI6Ii8yMTI1NTM0NC8zMzAzNjA5NDAtYmExMTJmN2MtYWYzZS00MmEzLTk4YWUtNTY3YTM0OTlmNjBlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3NTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTAxNGQyMTczYWRjMjRiY2ZiZjlhYjNjZWJkN2M1OTAwMmE4YTNhMzJmOWQ1M2MyNTVkNmI2MzJhMzFlMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D-c57xpUYTZM9LH6GGcRKn-tUHL8SvB9BGT6eTUPHN4)
> 
> 大佬这个怎么解决的？

你可以fork 一下他这个库然后替换成AF4.0 pod 地址指向你fork 的仓库地址

**Comment by gzx543097079** [comment]
已经修改为最新版本 4.0.1.1
